project:
  type: website
  output-dir: docs

website:
  title: "Effect of evening light on sleep"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Chang et al. 2014"
        contents:
          - href: chang14_experimental_results.qmd
            text: "Experimental results"
          - href: chang14_light_schedule.qmd
            text: "Light schedule"
      - section: "Sleep model"
        contents:
          - href: skeldon23_forced_wakeup.qmd
            text: "Forced wake-up"
          - href: skeldon23_parameter_exploration.qmd
            text: "Parameter exploration"
          - href: skeldon23_on_chang14.qmd
            text: "Simulations on Chang14 light schedule"
      - section: "Melatonin suppression model"
        contents:
          - href: melatonin_breslow13.qmd
            text: "Melatonin suppression model"
          - href: melatonin_breslow13_on_chang14.qmd
            text: "Simulations on Chang14 light schedule"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: minty
    css: styles.css
    toc: true



